### ISSUE TITLE
Setup and use logging for server

### ISSUE THREAD

**Issue by Baschdl** [KDD-OpenSource/32de-python#16]
The server does not support debug logging, yet. This should be implemented.

**AS A** Developer **I WOULD** like to be able to view debug outputs in a log file of a running server **SO THAT** access to the stdout is not necessary and debugging is possible.

**Comment by feeds** [comment]
I wouldn't use 'instead' here - printing important things on the concole is a good thing [and suggested by python](https://docs.python.org/3/howto/logging.html)
Still, importing the logger and setting up levels for less important but useful debug messages would be good.

**Comment by Baschdl** [comment]
I don't see where python suggests this. Do you mean this table?

Task you want to perform | The best tool for the task
-- | --
Display console output for ordinary usage of a command line script or program | print()

This is especially focused on command line programs. 
I think our system will be rather complex in the end, so it would be good to have a organised printing/logging from the beginning.

**Comment by MkuuWaUjinga** [comment]
DONE
