### ISSUE TITLE
Setup Coveralls

### ISSUE THREAD

**Issue by GittiHab** [KDD-OpenSource/32de-python#17]
I have tried setting up Coveralls using the Python `coveralls` plugin – but it seems to have some difficulties running in Docker. Maybe someone can look over it.

There is a branch `coveralls` which should already contain some configuration. The repository is already connected to Coveralls.io. Should you have trouble seeing the Repo/Organization there try to make your membership in the Organization public (More on how to solve this [here](https://github.com/lemurheavy/coveralls-public/issues/199) – especially around the part where the issue was originally closed).

**Comment by Baschdl** [comment]
Could you please describe your problems further?

**Comment by Baschdl** [comment]
Please talk with us 😉 We would save time if we wouldn't test the exact same things repeatedly like using directly travis without Docker, this won't work because travis uses a Ubuntu version where `graph-tool` is broken.

**Comment by GittiHab** [comment]
@Baschdl Following the instructions on the [Python Coveralls](https://github.com/z4r/python-coveralls) module it turns out that it expects to be run directly in Travis – that's why I just wanted to try that out but, as you pointed out, graph-tool doesn't like that. If you like, you can look into the error log on Travis before I removed the docker part.

**Comment by GittiHab** [comment]
Trying to talk to you is exactly what I have been trying to do by opening this issue.

**Comment by GittiHab** [comment]
This [Travis build](https://travis-ci.org/KDD-OpenSource/32de-python/builds/336490059) is especially helpful. Of course, you can probably test it locally but I have been having trouble there, too.

There is probably some solution somehow but I am not sure if it's worth it.

**Comment by Baschdl** [comment]
"Friday is burger day" (@wgierke) so it would be a shame to not work today 😁  Isn't https://github.com/z4r/python-coveralls/issues/59 a promising issue for our problem?

**Comment by GittiHab** [comment]
@Baschdl work yes, but on this? Seems to be promising. But I have already invested enough time on this today, I actually planned on doing other things. Maybe you can take a look and make Travis happy again 😉 (I really hate GitHubs emoji support where you have to know the names of them)

**Comment by Baschdl** [comment]
I probably also have no time for this today

**Comment by WGierke** [comment]
I also planned on having a nice Friday burger with some friends today but life isn't always a bowl of cherries.

**Comment by GittiHab** [comment]
I have added a documentation on Travis/Docker for the future https://github.com/KDD-OpenSource/32de-python/wiki/Continuous-Integration-and-Docker

**Comment by GittiHab** [comment]
Runs locally... but not on Travis.

**Comment by Baschdl** [comment]
The first idea for debugging is to print the file on travis with `cat`.

**Comment by GittiHab** [comment]
Sadly, this didn't tell us anything new. [Link to Travis build](https://travis-ci.org/KDD-OpenSource/32de-python/builds/341349758)

**Comment by Baschdl** [comment]
Travis goes into the `32de-python`-folder by running `cd KDD-OpenSource/32de-python` when running `git clone --depth=50 --branch=coveralls https://github.com/KDD-OpenSource/32de-python.git KDD-OpenSource/32de-python`. So it can't find the python file in `/32de-python/active_learning/__init__.py` because this file is in `active_learning/__init__.py`.

**Comment by GittiHab** [comment]
The path prefix `/32de-python/...` comes from Docker as this is the absolute path the file in the container. Whereas in travis the absolute file would be `/OpenSource/32de-python/...`

**Comment by Baschdl** [comment]
But it would be sufficient to use the relative path `...` (in your example), so for example `active_learning/__init__.py` and everything would be fixed?

**Comment by GittiHab** [comment]
I am not the one specifying the path – it is the coverage module of python doing it. I indeed specified a relative path in `.coveragerc` that should be used when merging `.coverage` file (these are the generated one with the absolute path). This is also what it does locally which is why it works locally.

**Comment by GittiHab** [comment]
OK, I manually replaced it now... that "fixes" the issue.

**Comment by GittiHab** [comment]
GitHub doesn't seem to have noticed that the PR solved this.

**Comment by Baschdl** [comment]
Nice work :D
