### ISSUE TITLE
Sync Docker Container with Code

### ISSUE THREAD

**Issue by GittiHab** [KDD-OpenSource/32de-python#20]
AS A Developer
I WANT to be able to sync my changes project files into the docker container
SO THAT I don't have to rebuild the whole image to test every small change.

This could be done either via `docker cp` which simply copies the files into the container (this is not working for me on Mac) or by mounting a volume into the Docker container.

**Comment by Baschdl** [comment]
Is the rebuilding the problem or the time the rebuilding takes?

**Comment by GittiHab** [comment]
Both – the rebuilding should, out of my perspective not be necessary. And time is always a problem.

**Comment by Baschdl** [comment]
1. That's probably correct for this repository but doesn't hold for our neo4j graph algorithm changes.
2. As I said we can improve the building time by "caching" the python requirements from requirements.txt by finding some way to not use the uncachable file (in the worst case by "hardcoding" the libraries in the Dockerfile).
III. I think it has a higher priority to get the complete Docker environment up and running before improving it.

**Comment by GittiHab** [comment]
This will be continued/improved in #54. #48 solved this.
